### ISSUE TITLE
compilation trouble

### ISSUE THREAD

**Issue by shirish47** [loboris/ESP32_spiffs_example#5]
I configured with make menuconfig then executed make flash 
it was compiling then I got 
```
...
AR libmdns.a
CC micro-ecc/uECC.o
AR libmicro-ecc.a
AR libmkspiffs.a
usage: mkdir [-pv] [-m mode] directory ...
make[1]: *** [build] Error 64

```

**Comment by shirish47** [comment]
what do I do for this?

**Comment by lucadentella** [comment]
Hi, if you update your esp-idf installation from Github it should work fine

**Comment by shirish47** [comment]
thank you very much I did and it worked.
