### ISSUE TITLE
How to create the image with Windows?

### ISSUE THREAD

**Issue by bospre** [loboris/ESP32_spiffs_example#7]
Hello,
sorry for the stupid question, but I did not figure out, how to create an image and how it is uploaded to the ESP32?
Maybe sombody can help to get into the right direction.
Commands like "make makefs" do not work under Windows.
For the ESP8266 there is a plugin for the arduino IDE, but that does not work for the ESP32.

Sincerely
Boris

**Comment by pushtoopen** [comment]
I use a linux virtual machine, msys2 (this is what esp32 recommends) the makefs commands work in that environment.
