### ISSUE TITLE
error when compiling

### ISSUE THREAD

**Issue by orcim** [loboris/ESP32_spiffs_example#9]
hi,

I found this error when compiling:

ESP32_spiffs_example-master/components/spiffs/./spiffs_vfs.c:836:9: error: unknown field 'fd_offset' specified in initializer
         .fd_offset = 0,

BR,
Loris

**Comment by orcim** [comment]
hi,
I've found it.

in the new version of "esp_vfs.h" dont exist  'fd_offset'.
the solution is comment this line.

BR,
Loris

**Comment by loboris** [comment]
Fixed in latest commit.
